// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Tour struct {
	ID             uuid.UUID
	Name           string
	Slug           sql.NullString
	Duration       sql.NullString
	Maxgroupsize   int32
	Difficulty     string
	Ratingaverage  sql.NullString
	Ratingquantity sql.NullInt32
	Price          int32
	Discount       sql.NullString
	Summary        string
	Description    sql.NullString
	Imagecover     sql.NullString
	Createdat      time.Time
	Startdates     []time.Time
	Secrettour     sql.NullBool
}
